version: "2"
services:
    www:
        image: servphp7-1:1.1
        ports: 
            - "8002:80"
        depends_on:
            - db
        volumes:
            - ./cbt:/var/www/html/
        links:
            - db:db
        networks:
            - default
    db:
        image: mysql:5.7
        ports: 
            - "3307:3306"
        environment:
            MYSQL_DATABASE: flyexam
            MYSQL_USER: root
            MYSQL_PASSWORD: 0987654321
            MYSQL_ROOT_PASSWORD: 0987654321
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8001:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: 0987654321
            MYSQL_ROOT_PASSWORD: 0987654321
volumes:
    persistent:
